services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - '${API_PORT}:${API_PORT}'
    depends_on:
      - mongo
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MONGODB_URI=mongodb://mongo:27017/remnote_notification_plugin #create diff env file
      - SCHEDULER_INTERVAL_MS=${SCHEDULER_INTERVAL_MS}
    volumes:
      - ./server:/app/server
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
