services:
  server:
    platform: linux/amd64
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - '${API_PORT}:${API_PORT}'
    depends_on:
      - mongo
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MONGODB_URI=${MONGODB_URI}
      - SCHEDULER_INTERVAL_MS=${SCHEDULER_INTERVAL_MS}
    volumes:
      - ./server:/app/server
      - ./server/logs:/app/logs
    restart: always

  mongo:
    platform: linux/amd64
    build:
      context: ./mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
