name: Unit Tests

on:
  push:
    branches:
      - master
    pull_request:
      - master

jobs:
  tests-plugin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: plugin
        run: |
          pnpm install

      - name: Run unit tests
        working-directory: plugin
        run: |
          pnpm test

  tests-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: server
        run: |
          pnpm install

      - name: Run unit tests
        working-directory: server
        run: |
          pnpm test
